[project]
name = "paulorodrigues-blog"
version = "0.1.0"
description = "Blog pessoal de Paulo Rodrigues"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-macros-plugin>=1.5.0",
    "mkdocs-material>=9.6.12",
]
